#Config
server.port: 8085
spring.profiles.active: local
server.error.include-message: always

#prometheus
management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include:
  - health
  - info
  - env
  - prometheus
   
#datasource
spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa.database-platform: org.hibernate.dialect.H2Dialect
