DROP TABLE IF EXISTS TB_PESSOA;
DROP TABLE IF EXISTS TB_CONTA;
DROP TABLE IF EXISTS TB_TRANSACAO;

CREATE TABLE TB_PESSOA (
    ID_PESSOA BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

INSERT INTO TB_PESSOA (CPF, DATA_NASCIMENTO, NOME) VALUES
  ('12345678901', '1995-01-25', 'Dangote'),
  ('09876543212', '1987-10-15', 'Gates'),
  ('12124531233', '2000-05-30', 'Alakija');

CREATE TABLE "TB_CONTA"(
    "ID_CONTA" BIGINT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE "TB_TRANSACAO"(
    "ID_TRANSACAO" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "DATA_TRANSCAO" TIMESTAMP
);
