DROP TABLE IF EXISTS TB_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_CONTA CASCADE;
DROP TABLE IF EXISTS TB_TRANSACAO CASCADE;

CREATE TABLE TB_PESSOA (
    ID_PESSOA BIGINT AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

INSERT INTO TB_PESSOA (CPF, DATA_NASCIMENTO, NOME) VALUES
  ('12345678901', '1995-01-25', 'Dangote'),
  ('09876543212', '1987-10-15', 'Gates'),
  ('12124531233', '2000-05-30', 'Alakija');

CREATE TABLE TB_CONTA (
    ID_CONTA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PESSOA BIGINT,
    SALDO DECIMAL(15,2) NOT NULL,
    LIMITE_SAQUE_DIARIO DECIMAL(15,2),
    FLAG_ATIVO BOOLEAN NOT NULL,
    TIPO_CONTA INTEGER NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL
);

ALTER TABLE TB_CONTA
ADD CONSTRAINT FK_PESSOA_CONTA
FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA);

CREATE TABLE TB_TRANSACAO (
    ID_TRANSACAO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_CONTA BIGINT,
    VALOR DECIMAL(15,2) NOT NULL,
    DATA_TRANSCAO TIMESTAMP NOT NULL
);

ALTER TABLE TB_TRANSACAO
ADD CONSTRAINT FK_CONTA_TRANSACAO
FOREIGN KEY (ID_CONTA) REFERENCES TB_CONTA(ID_CONTA);